### ISSUE TITLE
安装报错。并且我不想让我整个目录都777

### ISSUE THREAD

**Issue by mario-huang** [weexteam/weex-previewer#2]
> weex-previewer@1.3.10-beta3 postinstall /usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer
> node ./src/hook/post-install.js

Error:permission denied.Please apply the write premission to the directory: "/Users/xxx"

**Comment by erha19** [comment]
You can delete `~/.xtoolkit` and re-install `weex-toolkit`, this may skip this error.
